# Generated by Django 4.1.13 on 2024-08-25 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIAGNOSTICO',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_diagnostico', models.DateTimeField()),
                ('nivel_gravedad', models.CharField(max_length=20)),
                ('observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HONGO',
            fields=[
                ('id_hongo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('tratamiento_recomendado', models.TextField()),
                ('nombre_comun', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('domicilio', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TRATAMIENTO',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_tratamiento', models.DateTimeField()),
                ('tipo_tratamiento', models.CharField(max_length=50)),
                ('resultado', models.CharField(max_length=50)),
                ('seguimiento_requerido', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='PLANTA',
            fields=[
                ('id_planta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('estado_salud_sano', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='IMAGEN',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_imagen', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField()),
                ('id_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.planta')),
            ],
        ),
        migrations.CreateModel(
            name='HISTORIAL_TRATAMIENTO',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_aplicacion', models.DateTimeField()),
                ('resultado', models.CharField(max_length=50)),
                ('notas', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.planta')),
                ('id_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.tratamiento')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='id_hongo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.hongo'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='id_planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.planta'),
        ),
    ]
